AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
