version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - RAILS_ENV=development
    volumes:
      - ../:/app
    stdin_open: true
    tty: true
