casos_solicitudes:
  tr01:
    email: hclazarte@noexiste.com
    comercio:
      id: 53257
      ciudad_id: 7
      zona_id: 5
      zona_nombre: 'SAN PEDRO'
      calle_numero: 'AV. 20 DE OCTUBRE Nº 1839'
      planta: null
      numero_local: null
      telefono1: null
      palabras_clave: null
      telefono2: null
      telefono_whatsapp: '59170513586'
      pagina_web: null
      servicios: 'DISEÑO Y DESARROLLO DE SOFTWARE EN EL ÁREA DE SISTEMAS DE INFORMACIÓN GEOGRAÁFICA, SERVICIOS INFORMÁTICOS, ALOJAMIENTO DE PAGINAS WEB, PUBLICIDAD POR INTERNET, PUBLICIDAD POR CELULARES Y/O TELÉFONOS MOVILES, PUBLICIDAD POR TRANSPORTE PÚBLICO , SERVICIO DE LOCALIZACIÓN GEOGRÁFICA, INFORMACIÓN GEOREFERENCIADA, CONSULTORÍAS RELATIVAS A LA MATERIA Y CUALQUIER OTRO SERVICIO EN EL RAMO'
      contacto: null
      email: 'hclazarte@hotmail.com'
      documentos_validados: 0
      autorizado: 0
      email_verificado: null
  tr02:
    email: jackyfukushima@gmail.com
    comercio:
      id: 53258
      ciudad_id: 44
      zona_id: 31
      zona_nombre: 'CENTRAL'
      calle_numero: 'AYACUCHO Nº s/n'
      planta: null
      numero_local: null
      telefono1: null
      palabras_clave: null
      telefono2: null
      telefono_whatsapp: '59172300013'
      pagina_web: null
      servicios: null
      contacto: null
      email: 'jackyfukushima@gmail.com'
      documentos_validados: 0
      autorizado: 0
      email_verificado: null
  tr03:
    email: gloriaalcazarleyton@gmail.com
    comercio:
      id: 87642
      ciudad_id: 54
      zona_id: null
      zona_nombre: 'CENTRAL'
      calle_numero: 'AV. BUSCH Nº 50'
      planta: null
      numero_local: null
      telefono1: '9523069'
      palabras_clave: null
      telefono2: null
      telefono_whatsapp: null
      pagina_web: null
      servicios: 'VENTA DE MEDICAMENTOS'
      contacto: 'FARMACEUTICA MAMAN'
      email: 'gloriaalcazarleyton@gmail.com'
      documentos_validados: 1
      autorizado: 0
      email_verificado: null
    solicitud:
      estado: documentos_validados
      otp_expires_at_testdate_offset: "+1h"      # token válido por ahora
      nit_ok: true
      ci_ok: true
      nombre: 'Gloria Alcázar Méndez'
  tr04:
    email: milton.ortuno@bie.com.bo
    comercio:
      id: 18115
      ciudad_id: 25
      zona_id: 94
      zona_nombre: 'BARRIO LINDO'
      calle_numero: 'C/ TENIENTE RIVERO, ESQUINA CUELLAR Nº 187'
      planta: null
      numero_local: null
      telefono1: null
      palabras_clave: null
      telefono2: null
      telefono_whatsapp: '59172125050'
      pagina_web: null
      servicios: 'SERVICIOS MÉDICOS HOSPITALARIOS DE 1ER, 2DO Y 3ER NIVEL.- NEFROLOGÍA (HEMODIÁLISIS, DIÁLISIS PERITONEAL, HEMO FILTRACIÓN, PLASMAFÉRESIS, HEMODIÁLISIS PORTÁTIL).- UROLOGÍA - CARDIOLOGÍA - TERAPIA INTENSIVA ÚTI - CIRUGÍA VASCULAR - NEUROLOGÍA - RADIOLOGÍA (RAYOS X, TOMOGRAFÍA, RADIOTERAPIA, ACELERADOR LINEAL) - MEDICINA CLÍNICA. - PSICOLOGÍA - NUTRICIÓN - LABORATORIOS ANÁLISIS CLÍNICOS. - INVESTIGACIÓN, DESARROLLO Y PRODUCCIÓN BIOQUÍMICA FARMACÉUTICA Y BIOLÓGICA MOLECULAR GENÉTICA. - DESARROLLO'
      contacto: 'BIOINGENIERIA ESPECIALIZADA SRL BIESRL'
      email: 'milton.ortuno@bie.com.bo'
      documentos_validados: 1
      autorizado: 1
      email_verificado: null
    solicitud:
      estado: documentos_validados
      fecha_fin_servicio_testdate_offset: "+30d"   # plan vigente 30 días más
      nit_ok: true
      ci_ok: true
      nombre: 'Miltón Ortuño'
  tr05:
    email: granicorp016@gmail.com
    comercio:
      id: 18036
      ciudad_id: 24
      zona_id: 45
      zona_nombre: 'MUYURINA'
      calle_numero: 'AVENIDA ANICETO ARCE Nº 611'
      planta: null
      numero_local: null
      telefono1: '4227157'
      palabras_clave: null
      telefono2: null
      telefono_whatsapp: null
      pagina_web: null
      servicios: 'EXPORTACION DE CEREALES Y OLEAGINOSAS'
      contacto: 'GRANICORP'
      email: 'granicorp016@gmail.com'
      documentos_validados: 1
      autorizado: 1
      email_verificado: null
    solicitud:
      estado: documentos_validados
      otp_expires_at_testdate_offset: "+1h"      # token válido
      nit_ok: true
      ci_ok: true
      nombre: 'Jorge Rojas'
  tr06:
    email: tr06.vencido@gmail.com
    comercio:
      id: 32184
    solicitud:
      estado: documentos_validados
      otp_expires_at_testdate_offset: "-1h"   # token expirado
